### ISSUE TITLE
examples/form: losing current input value during validation

### ISSUE THREAD

**Issue by justinfx** [jfyne/live#6]
I'm exploring the examples in the project and noticed that in the examples/form, when typing less than 10 characters we get the proper validation error message. But once we cross the length of 10 character and the error div clears, so does the current value in the input text field. I've been trying to figure out the way to preserve this value in Live and can't tell if its something straightforward on the client page side, or something specific to the Live dom updates not preserving the text input value. I've also tried to add a form struct field to capture the `LastMessage` and propagate it back to the input value, but that has the unwanted effect of the cursor position staying at the 0 index as you type, and get backwards values.
Is it possible to update the examples/form to show how to properly preserve the input value when the validation logic swaps away the error div?

I'm testing this in latest Chrome on Ubuntu and Go 1.15.5

**Comment by justinfx** [comment]
Actually, I realized I am getting a console error from that example at the moment when the characters reach 10:

```
patch.ts:35 Uncaught TypeError: Cannot read property 'childNodes' of undefined
    at applyPatch (patch.ts:35)
    at Array.map (<anonymous>)
    at Function.handle (patch.ts:18)
    at WebSocket.<anonymous> (socket.ts:49)
```

**Comment by jfyne** [comment]
Hi, oops I will have a look

**Comment by jfyne** [comment]
This should be fixed now. It was a diff case I hadn't thought about, and I hadn't checked the form example in a while, Please try the new release. Thanks!

**Comment by justinfx** [comment]
The original issue is now fixed, so that it retains the input value when toggling the error message. But I see that it still hits the same error in the console after submitted the 3rd time. Does that happen for you as well?

**Comment by jfyne** [comment]
I didn't see that, but I will have another look. 

Thanks for finding these!

**Comment by jfyne** [comment]
Ok I think I see it in an old version. If the range of `<pre>` tags are being output without being wrapped in a container i see the error message. Temp fix is to just wrap them in a container like they are on master.

Issue is to do with how the server side diff function is dealing with white space. I'm trying to figure out a fix now, I will get back to you

**Comment by jfyne** [comment]
Ok please try the latest master or `v0.2.1` and see if it is fixed for you. Thanks

**Comment by justinfx** [comment]
Works great now. Thanks!

**Comment by c-nv-s** [comment]
just tried the ToDo list example on firefox 83.0
seems like it's still producing console errors:

![golivetodolisterrors](https://user-images.githubusercontent.com/7495833/103481291-51789b80-4dda-11eb-9de2-4a715b20c83a.gif)

```
WebSocket Disconnected code: 1001, reason: live.js:1:7184
Cookie “session-name” has been rejected because a non-HTTPS cookie can’t be set as “secure”. form
Socket.dial called socket.ts:18:16
GEThttp://10.139.71.29:8081/favicon.ico
[HTTP/1.1 404 Not Found 0ms]

Uncaught TypeError: e.getAttribute is not a function
    hook element.ts:31
    getElementHooks event.ts:150
    beforeDestroy event.ts:98
    applyPatch patch.ts:59
    handle patch.ts:18
    dial socket.ts:51
    dial socket.ts:43
    w live.ts:12
    <anonymous> auto.ts:16
    EventListener.handleEvent* auto.ts:11
    <anonymous> auto.ts:16
element.ts:31:23
Uncaught TypeError: e.getAttribute is not a function
    hook element.ts:31
    getElementHooks event.ts:150
    beforeDestroy event.ts:98
    applyPatch patch.ts:59
    handle patch.ts:18
    dial socket.ts:51
    dial socket.ts:43
    w live.ts:12
    <anonymous> auto.ts:16
    EventListener.handleEvent* auto.ts:11
    <anonymous> auto.ts:16
element.ts:31:23
Uncaught TypeError: e.getAttribute is not a function
    hook element.ts:31
    getElementHooks event.ts:150
    beforeDestroy event.ts:98
    applyPatch patch.ts:59
    handle patch.ts:18
    dial socket.ts:51
    dial socket.ts:43
    w live.ts:12
    <anonymous> auto.ts:16
    EventListener.handleEvent* auto.ts:11
    <anonymous> auto.ts:16
element.ts:31:23
Uncaught TypeError: e.getAttribute is not a function
    hook element.ts:31
    getElementHooks event.ts:150
    beforeDestroy event.ts:98
    applyPatch patch.ts:59
    handle patch.ts:18
    dial socket.ts:51
    dial socket.ts:43
    w live.ts:12
    <anonymous> auto.ts:16
    EventListener.handleEvent* auto.ts:11
    <anonymous> auto.ts:16
element.ts:31:23
```
​

**Comment by jfyne** [comment]
@c-nv-s try latest master or release `v0.2.5`.

It appears Firefox doesn't have `getAttribute` defined everywhere. Should be fixed now

**Comment by jfyne** [comment]
Actually found another bug off the back of that, again appears to be just firefox

**Comment by jfyne** [comment]
@c-nv-s Ok now Firefox works, thanks for the headsup

**Comment by c-nv-s** [comment]
v0-2-5 firefox 83.0 - console errors resolved if you ignore duplicating 'submit query' button
I don't have [screenkey](https://gitlab.com/screenkey/screenkey) enabled but I can assure you I'm not pressing Enter during this demo:

![jfyne-live-v0-2-5-issue6](https://user-images.githubusercontent.com/7495833/103484497-7d524c00-4def-11eb-8b74-8ab02b98a1f8.gif)

**Comment by jfyne** [comment]
Hmm that's just what I though I fixed... Let me try and replicate again

**Comment by jfyne** [comment]
Oh try `v0.2.6` that's where the fix for that is

**Comment by c-nv-s** [comment]
v0-2-6-issue06-02.gif firefox 83.0 : as far i'm concerned this ticket is resolved for firefox.

![jfyne-live-v0-2-6-issue6-02](https://user-images.githubusercontent.com/7495833/103491218-20bc5480-4e22-11eb-8cfb-27a8e2b19af8.gif)


As you have also noticed there is hesitation to connect to the websocket, and I initially receive a series of connection not ready errors, however that's for a separate ticket.
```
connection not ready for send of event  Object { t: "validate", d: {…} }      socket.ts:62:20
```

**Comment by jfyne** [comment]
Great, thanks!
