### ISSUE TITLE
Broadcasting events on global level?

### ISSUE THREAD

**Issue by dmarko484** [jfyne/live#61]
Hi,
is there a way how to use broadcasting events on app global level? I mean, in app we are using live.Socket.Broadcast for sending information to all connected users. This is related to live.Socket from particular user, so its user triggered event actually. What if we would like to broadcast general events like "current time" to all connected users. When Live app starts, we should start broadcasting events. Is there way how to do it right now? Hopefully it's clear ...

David

**Comment by jfyne** [comment]
Hi there, I just added an example of how to do this:

https://github.com/jfyne/live-examples/blob/57934f4c519d685cda2db1e6894defde54ba4100/chat/cmd/chat/main.go#L14-L20

This adds a message every minute in the chat example broadcast to all connected

![2023-01-03-17-11-24](https://user-images.githubusercontent.com/400281/210406625-0f1b6e10-33b0-41e4-91b8-04020740af89.png)

**Comment by dmarko484** [comment]
Amazing, such a quick answer. It's exactly what I need! Great project!

**Comment by jfyne** [comment]
My pleasure!
