### ISSUE TITLE
Integration with Fiber

### ISSUE THREAD

**Issue by dmarko484** [jfyne/live#64]
Hi,
I'v created a pull request some time ago for fixing integration issues with recent Fiber framework. Its in contrib repo see here https://github.com/jfyne/live-contrib/pulls . Can anyone take a look at it, please? If there is any issue with it, I can update this pull request, if needed.

Btw: I still must say, it's an amazing project! Needs more publicity.

thank you,
David

**Comment by jfyne** [comment]
Done, also updated to 0.15.4

**Comment by dmarko484** [comment]
Great, thanks.
